spring:
  application:
    name: aopwithrest
  datasource:
    url: jdbc:postgresql://localhost:5432/telusko
    username: postgres
    password: passer
    #hikari:
      #auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081