spring:
  application:
    name: spring-sec-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/telusko
    username: postgres
    password: passer
    hikari:
      auto-commit: false
  security:
    user:
      name: telusko
      password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    session:
      cookie:
        same-site: strict