spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: postgres
    password: passer
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

server:
  port: 8090