version: "3.7"
services:
  app:
    build: .
    ports:
      - "8090:8090"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
      POSTGRES_DB: telusko
    ports:
      - "5433:5432"
    networks:
      - s-network
    volumes:
    - postgres-s-data:/var/lib/postgresql/data
    
networks:
  s-network:
    driver: bridge
volumes:
  postgres-s-data: